$inherits:
  from: 'tasks/build.yml'
  variables:
    build_product: 'firefox'
task:
  scopes:
    - "secrets:get:project/releng/gecko/build/level-{{level}}/*"
  extra:
    locations:
      mozharness: 'public/build/mozharness.zip'
      test_packages: 'public/build/test_packages.json'
    features:
      taskclusterProxy: true
